---
title: "NEWS: nser"
author: "Nandan Patil"
date: "7/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# WELCOME

Visit website for examples and more info [nser](https://nandp1.github.io/nser/)

## Version `1.5.3`

* Due to change in NSE website interface the bhav function has been revised from 1.5.3 and old code is maintained in bhav1.
* bhav downloads bhavcopy from 1 Jan 2020 onwards,
* bhav1 downloads NSE bhavcopy from from 1 Jan 2016 to 05 July 2024.

## Version `1.5.2`

* Minor changes in function `nselive`, `nseopen`

## Version `1.5.1`

* Minor changes in function `bhav`

## Version `1.5.0`

* Revised function `nselive`, `nseopen` `nseindex`, `nsetree`, `optbanknifty` and `optnifty` obtain data from NSE using python scripts.

## Version `1.3.5`

* New function `daytomonth`

## Version `1.3.4`

* Minor modification in `daytoweek`

## Version `1.3.3`

* New function `daytoweek` to convert daily data to montly data. 

## Version `1.3.2`

* `optbanknifty`  and `optnifty` are deprecated. 


## Version `1.3.1`

* `optbanknifty` Minor changes.

## Version `1.3.0`

* New functions `nsetree`, `optnifty`, `optbanknifty`, `bhavfos`

* `nsetree` Get a treeplot plot of NSE NIFTY 50 and FO securities. 

* `optnifty` Option chain of NIFTY 50 for the current expiry. 

* `optbanknifty` Option chain of BANKNIFTY for the current expiry. 

* `bhavfos` Download historical F&O Bhavcopy zip file through RSelenium. 

## Version `1.2.1`

* Minor corrections in ```nseindex```, ```nselive```, ```nseopen```. 

## Version `1.2.0`

* New function ```bhavs``` to download bhavcopy zipfile using RSelenium.

## Version `1.1.0`

* New functions ```nseindex```

## Version `1.0.0`

* First version 0.1.0 with  functions to download Equity, Futures and Derivatives(F&O) Bhavcopy from NSE. 








